// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Muhammad Ahyaruddin",
            "email": "ahyaruddin07@gmail.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/scrape/youtube/play": {
            "post": {
                "description": "Opens a YouTube URL in a browser, clicks the play button, and logs the result to MongoDB.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "scrape"
                ],
                "summary": "Scrape a YouTube video",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "Run browser in headless mode",
                        "name": "headless",
                        "in": "query"
                    },
                    {
                        "description": "Scrape request body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal.ScrapeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "internal.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 400
                },
                "errors": {
                    "type": "object",
                    "additionalProperties": true
                },
                "status": {
                    "type": "string",
                    "example": "BAD_REQUEST"
                },
                "success": {
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "internal.ScrapeData": {
            "type": "object",
            "properties": {
                "action": {
                    "type": "string",
                    "example": "CLICK_PLAY"
                },
                "logId": {
                    "type": "string",
                    "example": "64f000000000000000000000"
                },
                "message": {
                    "type": "string",
                    "example": "YouTube video play button clicked successfully"
                },
                "result": {
                    "type": "string",
                    "example": "SUCCESS"
                },
                "url": {
                    "type": "string",
                    "example": "https://www.youtube.com/watch?v=abc123"
                }
            }
        },
        "internal.ScrapeRequest": {
            "type": "object",
            "required": [
                "url"
            ],
            "properties": {
                "proxy": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "internal.SuccessResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 200
                },
                "data": {
                    "$ref": "#/definitions/internal.ScrapeData"
                },
                "status": {
                    "type": "string",
                    "example": "OK"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "YouTube Watcher API",
	Description:      "YouTube scraping service that opens a YouTube URL in a browser, clicks play, and logs to MongoDB.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
